version: "3"
networks:
  crypto-alerts-network:

services:
  
  mongoDB:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /var/lib/docker/volumes/mongodb_volume/_data:/data/db

  worker-prices:
    image: node:9-slim
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongoDB
    links:
      - "mongoDB:mongoDB"
    command: node worker-prices/worker.js
    env_file:
      - default.env

  worker-telegram:
    image: node:9-slim
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongoDB
    links:
      - "mongoDB:mongoDB"
    command: node worker-telegram/worker.js
    env_file:
      - default.env

  # The actual client application
  web-server-container:
    image: node:9-slim
    working_dir: /usr/src/app
    command: node app.js
    depends_on:
      - mongoDB
    links:
      - "mongoDB:mongoDB"
    
    # make sure the mounted volume path is of the app's directory
    volumes:
      - .:/usr/src/app
    ports:
      - 80:80
    env_file:
      - default.env
