version: "2"

services:
  mongoDB:
    image: mongo
    mem_limit: 200m
    ports:
      - 27017:27017
    volumes:
      - /var/lib/docker/volumes/mongodb_volume/_data:/data/db

  worker-prices:
    image: 263846239257.dkr.ecr.us-west-1.amazonaws.com/crypto-alert-images
    mem_limit: 200m
    working_dir: /usr/src/app
    
    depends_on:
      - mongoDB
    links:
      - "mongoDB:mongoDB"
    command: node worker-prices/worker.js
    env_file:
      - default.env
    environment:
      - APP_STARTUP=worker-prices/worker.js
      - ENVIRONMENT=prod

  worker-telegram:
    image: 263846239257.dkr.ecr.us-west-1.amazonaws.com/crypto-alert-images
    mem_limit: 200m
    working_dir: /usr/src/app
    depends_on:
      - mongoDB
    links:
      - "mongoDB:mongoDB"
    command: node worker-telegram/worker.js
    env_file:
      - default.env
    environment:
      - APP_STARTUP=worker-telegram/worker.js
      - ENVIRONMENT=prod

  web-server-container:
    image: 263846239257.dkr.ecr.us-west-1.amazonaws.com/crypto-alert-images
    mem_limit: 200m
    working_dir: /usr/src/app
    command: node app.js
    depends_on:
      - mongoDB
    links:
      - "mongoDB:mongoDB"
    ports:
      - 80:80
    env_file:
      - default.env
    environment: 
      - APP_STARTUP=app.js
      - ENVIRONMENT=prod
