version: "3"

services:
  mongoDB:
    image: mongo
    ports:
      - 27017:27017

  telegram-container:
    image: crypto-alert-images:latest
    ports: 
      - 3001:3001
    working_dir: /usr/src/app
    environment:
      APP_STARTUP: 'telegramApp.js'
    #command: node telegramApp.js

  # The actual client application
  app-container:
    image: crypto-alert-images:latest
    working_dir: /usr/src/app
    #command: node app.js
    depends_on:
      - mongoDB
    links:
      - "mongoDB:mongoDB"
      - "telegram-container:telegram-container"

    #build: 
    #  context: .
    #  dockerfile: appDockerfile
    # make sure the mounted volume path is of the app's directory
    environment:
      ENV_NAME: dev
      DB_HOST: mongoDB
      TELEGRAM_API_KEY: 942311713:AAHObtynOoLLrP2f6g_s3Xb85n0ASLfNeRs
      BOT_NAME: '@CryptoTester67Bot'
      APP_STARTUP: 'app.js'
      # AWS_ACCESS_KEY_ID: 
      # AWS_SECRET_ACCESS_KEY: 
    ports:
      - 80:80
