version: "3"
networks:
  crypto-alerts-network:

services:
  
  mongoDB:
    image: mongo
    ports:
      - 27017:27017
#--------------------------------------------------------------------------------#
  worker-prices:
    image: node:9-slim
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongoDB
    links:
      - "mongoDB:mongoDB"
    command: node worker-prices/worker.js
    env_file:
      - default.env
#--------------------------------------------------------------------------------#
  worker-telegram:
    image: node:9-slim
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongoDB
    links:
      - "mongoDB:mongoDB"
    command: node worker-telegram/worker.js
    env_file:
      - default.env
#--------------------------------------------------------------------------------#
  web-server-container:
    image: node:9-slim
    working_dir: /usr/src/app
    command: node app.js
    depends_on:
      - mongoDB
    links:
      - "mongoDB:mongoDB"
    volumes:
      - .:/usr/src/app
    ports:
      - 80:80
    env_file:
      - default.env
