version: "2"

services:

  worker-prices:
    image: 263846239257.dkr.ecr.us-west-1.amazonaws.com/crypto-alert-images
    mem_limit: 200m
    working_dir: /usr/src/app
    command: node worker-prices/worker.js
    env_file:
      - default.env
    environment:
      - APP_STARTUP=worker-prices/worker.js
      - ENVIROMENT=prod

  worker-telegram:
    image: 263846239257.dkr.ecr.us-west-1.amazonaws.com/crypto-alert-images
    mem_limit: 200m
    working_dir: /usr/src/app
    command: node worker-telegram/worker.js
    env_file:
      - default.env
    environment:
      - APP_STARTUP=worker-telegram/worker.js
      - ENVIROMENT=prod

  web-server-container:
    image: 263846239257.dkr.ecr.us-west-1.amazonaws.com/crypto-alert-images
    mem_limit: 200m
    working_dir: /usr/src/app
    command: node app.js
    ports:
      - 80:80
    env_file:
      - default.env
    environment: 
      - APP_STARTUP=app.js
      - ENVIROMENT=prod
