version: "2"

services:
#--------------------------------------------------------------------------------#
  mongoDB:
    image: mongo
    mem_limit: 200m
    ports:
      - 27017:27017
    volumes:
      - /var/lib/docker/volumes/mongodb_volume/_data:/data/db
#--------------------------------------------------------------------------------#
  worker-prices:
    image: node
    mem_limit: 200m
    working_dir: /usr/src/app
    depends_on:
      - mongoDB
    links:
      - "mongoDB:mongoDB"
    command:  >
      sh -c "git clone https://github.com/Rafael17/cryptoalerts.git . &&
             npm install &&
             node worker-prices/worker.js"
    env_file:
      - default.env
    environment:
      - ENVIRONMENT=prod
#--------------------------------------------------------------------------------#
  worker-telegram:
    image: node
    mem_limit: 200m
    working_dir: /usr/src/app
    depends_on:
      - mongoDB
    links:
      - "mongoDB:mongoDB"
    command:  >
      sh -c "git clone https://github.com/Rafael17/cryptoalerts.git . &&
             npm install &&
             node worker-telegram/worker.js"
    env_file:
      - default.env
    environment:
      - ENVIRONMENT=prod
#--------------------------------------------------------------------------------#
  web-server-container:
    image: node
    mem_limit: 200m
    working_dir: /usr/src/app
    command:  >
      sh -c "git clone https://github.com/Rafael17/cryptoalerts.git . &&
             npm install &&
             node app.js"
    depends_on:
      - mongoDB
    links:
      - "mongoDB:mongoDB"
    ports:
      - 80:80
    env_file:
      - default.env
    environment: 
      - ENVIRONMENT=prod
