version: "2"

services:
  mongoDB:
    image: mongo
    ports:
      - 27017:27017
    mem_limit: 200m

  telegram-container:
    image: 263846239257.dkr.ecr.us-west-1.amazonaws.com/crypto-alert-images
    ports: 
      - 3001:3001
    working_dir: /usr/src/app
    mem_limit: 200m

    environment:
      APP_STARTUP: 'telegramApp.js'
      TELEGRAM_API_KEY: 942311713:AAHObtynOoLLrP2f6g_s3Xb85n0ASLfNeRs

  worker-container:
    image: 263846239257.dkr.ecr.us-west-1.amazonaws.com/crypto-alert-images
    ports: 
      - 3002:3002
    working_dir: /usr/src/app
    command: node workerApp.js
    mem_limit: 200m
    links:
      - "telegram-container:telegram-container"


  # The actual client application
  app-container:
    image: 263846239257.dkr.ecr.us-west-1.amazonaws.com/crypto-alert-images
    mem_limit: 200m
    working_dir: /usr/src/app
    #command: node app.js
    depends_on:
      - mongoDB
    links:
      - "mongoDB:mongoDB"
      - "telegram-container:telegram-container"
      - "worker-container:worker-container"

    #build: 
    #  context: .
    #  dockerfile: appDockerfile
    # make sure the mounted volume path is of the app's directory
    environment:
      ENV_NAME: dev
      DB_HOST: mongoDB
      APP_STARTUP: 'app.js'
      BOT_NAME: '@CryptoTester67Bot'
      # AWS_ACCESS_KEY_ID: 
      # AWS_SECRET_ACCESS_KEY: 
    ports:
      - 80:80
