version: "3"
networks:
  crypto-alerts-network:

services:
  
  mongoDB:
    image: mongo
    ports:
      - 27017:27017

  worker-prices:
    image: node:9-slim
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongoDB
    links:
      - "mongoDB:mongoDB"
    command: node worker-prices/worker.js
    environment:
      - DB_HOST=mongoDB
      - DB_PORT=27017
      - DB_NAME=node_login
      - AWS_REGION=us-west-1
      - TELEGRAM_API_KEY=942311713:AAHObtynOoLLrP2f6g_s3Xb85n0ASLfNeRs

  worker-telegram:
    image: node:9-slim
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongoDB
    links:
      - "mongoDB:mongoDB"
    command: node worker-telegram/worker.js
    environment:
      - DB_HOST=mongoDB
      - DB_PORT=27017
      - DB_NAME=node_login
      - TELEGRAM_API_KEY=942311713:AAHObtynOoLLrP2f6g_s3Xb85n0ASLfNeRs
      - AWS_REGION=us-west-1

  # The actual client application
  web-server-container:
    image: node:9-slim
    working_dir: /usr/src/app
    command: node app.js
    depends_on:
      - mongoDB
    links:
      - "mongoDB:mongoDB"
    
    # make sure the mounted volume path is of the app's directory
    volumes:
      - .:/usr/src/app
    ports:
      - 80:80
    environment: 
      - BOT_NAME=@CryptoTester67Bot
      - DB_HOST=mongoDB
      - DB_PORT=27017
      - DB_NAME=node_login
      - SERVER_PORT=80
      - AWS_REGION=us-west-1
      - TELEGRAM_API_KEY=942311713:AAHObtynOoLLrP2f6g_s3Xb85n0ASLfNeRs
