version: "2"

services:
  mongoDB:
    image: mongo
    mem_limit: 200m
    ports:
      - 27017:27017

  worker-prices:
    #image: node:9-slim
    image: 263846239257.dkr.ecr.us-west-1.amazonaws.com/crypto-alert-images
    mem_limit: 200m
    working_dir: /usr/src/app
    #volumes:
    #  - .:/usr/src/app
    depends_on:
      - mongoDB
    links:
      - "mongoDB:mongoDB"
    command: node worker-prices/worker.js
    environment:
      - DB_HOST=mongoDB
      - DB_PORT=27017
      - DB_NAME=node_login
      - APP_STARTUP=worker-prices/worker.js
      - AWS_REGION=us-west-1
      - TELEGRAM_API_KEY=942311713:AAHObtynOoLLrP2f6g_s3Xb85n0ASLfNeRs

  worker-telegram:
    #image: node:9-slim
    image: 263846239257.dkr.ecr.us-west-1.amazonaws.com/crypto-alert-images
    mem_limit: 200m
    working_dir: /usr/src/app
    #volumes:
    #  - .:/usr/src/app
    depends_on:
      - mongoDB
    links:
      - "mongoDB:mongoDB"
    command: node worker-telegram/worker.js
    environment:
      - DB_HOST=mongoDB
      - DB_PORT=27017
      - DB_NAME=node_login
      - APP_STARTUP=worker-telegram/worker.js
      - TELEGRAM_API_KEY=942311713:AAHObtynOoLLrP2f6g_s3Xb85n0ASLfNeRs
      - AWS_REGION=us-west-1

  web-server-container:
    #image: node:9-slim
    image: 263846239257.dkr.ecr.us-west-1.amazonaws.com/crypto-alert-images
    mem_limit: 200m
    working_dir: /usr/src/app
    command: node app.js
    depends_on:
      - mongoDB
    links:
      - "mongoDB:mongoDB"
    
    #volumes:
    #  - .:/usr/src/app
    ports:
      - 80:80
    environment: 
      - BOT_NAME=@CryptoTester67Bot
      - DB_HOST=mongoDB
      - DB_PORT=27017
      - DB_NAME=node_login
      - SERVER_PORT=80
      - APP_STARTUP=app.js
      - AWS_REGION=us-west-1
      - TELEGRAM_API_KEY=942311713:AAHObtynOoLLrP2f6g_s3Xb85n0ASLfNeRs
